### ISSUE TITLE
Innovations and shortcomings

### ISSUE THREAD

**Issue by CzarOfScripts** [CoffeeChaton/vscode-autohotkey-NekoHelp#12]
Hi! I want to start by saying thank you for your work. You have done a great job. I saw your Issues in the AHK Simple repository and decided to see what yours could do.
* The first thing I like is that you show the default value of the function parameters.
* [x] The second is the comments themselves, but I don't understand why, when you enter parameters, you don't show the comment from the function and what it returns?  
![image](https://user-images.githubusercontent.com/78804737/231003098-e93cc132-3d37-4c41-aa28-28a76cc16e69.png)
* [x] Third, not so significant, I don't understand why there is no space here? And so subjective... I never liked the style where `{` is on the same line with something, it impairs readability. If there is an option to move this character on a new line - great.
![image](https://user-images.githubusercontent.com/78804737/231003659-60ba5755-9ee9-48c5-90c8-7fa711029d92.png)
* [x] Outline shows #include, please make their display optional
![image](https://user-images.githubusercontent.com/78804737/231006060-8d4f60f6-04e3-4fe8-9ff6-9c46e3f2756c.png)
* [x] I do not understand why you highlight the paths to the libraries in a different color + I would like to be able to ctrl+click to go to the inlude file.
![image](https://user-images.githubusercontent.com/78804737/231006240-d2a14b28-9a61-4b2e-9765-33a4461b11c0.png)
* [x] I see some obscure method `_sho` that is not in [my class][1]
![image](https://user-images.githubusercontent.com/78804737/231007343-cbe673d9-818a-42b7-afaf-a3fe95554f24.png)
* [x] I don't see the prompts from [my Include][1]
![image](https://user-images.githubusercontent.com/78804737/231008289-9ac41022-19fb-46c0-8d3a-f80789e86826.png)
until I open the [Include file][1] in a new tab:
![image](https://user-images.githubusercontent.com/78804737/231008410-15b0fffa-47da-4ed2-a2e0-e78364fd1f26.png)
* [x] I see reference for functions, but not for classes and class methods
![image](https://user-images.githubusercontent.com/78804737/231009004-bbb8eeee-01de-424e-b7de-6059bbf9caae.png)
![image](https://user-images.githubusercontent.com/78804737/231009158-c9530cdf-3bc3-45fb-898c-e7cb2c28e99b.png)
* [x] #15
![image](https://user-images.githubusercontent.com/78804737/231009785-47c226e0-bdc3-41c1-a68d-a2275ad8e2e4.png)
In AHK Simple this was implemented:
![image](https://user-images.githubusercontent.com/78804737/231009976-b3c7a082-5bb4-4963-bc66-d5b619882570.png)

---
**And most importantly, do you plan to add design support for functions with JSDoc? I mean, if I want to describe parameters, what type I expect, some description.**

_I apologize for the English, I use a translator for the whole text, if something is not clear, write about it and I will try to reword it and thanks again for your work!_

[1]: https://gist.github.com/CzarOfScripts/0f35b616392b494a334b228348b4d35d

**Comment by Chutriel235** [comment]
The obscure method Problem and the prompts only after i open an include are some very limiting problems. It would be fantastic if this can besolved.

**Comment by CoffeeChaton** [comment]
## part-1 signature show return and doc

> The second is the comments themselves, but I don't understand why, when you enter parameters, you don't show the comment from the function and what it returns?

I just started to provide [SignatureHelp](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp#signaturehelp) recently, I think you suggest of the user experience is good, and the next version will provided of user def-function, but build-in function I need 1~2 weekends to check the online documentation.

## part-2 doc-style

> Third, not so significant, I don't understand why there is no space here? And so subjective... I never liked the style where { is on the same line with something, it impairs readability. If there is an option to move this character on a new line - great.

I plan to use the style of each function defined by the user to determine the displayed document style, and it will be ready in about 2~3 weeks.

## part-3 Outline of #include

> Outline shows #include, please make their display optional.

it's very simple.

## part-4 highlight

> I do not understand why you highlight the paths to the libraries in a different color

1. _line 11_, very look like bug, But I can't reproduce it, can you provide a minimal file with the _theme_ you are using?
2. I used to write it with reference to the one that seems to be the most semantic in TextMate.
3. When I chose the string semantics in the early days, I was prevented from completing the path by the `editor.quickSuggestions` preset option of vscode.
4. But now I can solve the completing in string.
5. I think it would be better to use string color matching for the path, because the old style of bracket matching of vscode will get out of control.

![vv](https://user-images.githubusercontent.com/63182963/231221247-ce925198-fb22-4e2d-a290-e198fc5eea42.png)


exp : `#Include %A_LineFile%\..\ahk_test{.ahk`

## part-5 goto include file

> I would like to be able to ctrl+click to go to the include file.

if you use an absolute path goto the definition file is easy, I forgot to provide it.

## part-6 core parsing error

> I see some obscure method `_sho` that is not in [my class](https://gist.github.com/CzarOfScripts/0f35b616392b494a334b228348b4d35d)

The parsing error introduced by [switch to support unicode](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/blob/main/CHANGELOG.md#v00322023-04-01), specifically, the `\b` semantics cannot be used when regexp considers non-ascii. At the same time, many of the original methods of exclusion have changed to the method of using the allow list. If you have similar problems, please let me know. These Nice fix, but I'm having a hard time spotting it without triggering.

## part-7 Resolution scope

> I don't see the prompts from [my Include](https://gist.github.com/CzarOfScripts/0f35b616392b494a334b228348b4d35d)
> until I open the [Include file](https://gist.github.com/CzarOfScripts/0f35b616392b494a334b228348b4d35d) in a new tab:

this is by design of [Privacy Statement part 3](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp#privacy-statement).
or you can use [Multi-root Workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces).

## part-8 find all reference of class

> I see reference for functions, but not for classes and class methods.

Because this is very performance consuming, the use of ahk class is almost as free as global variables, without very obvious features, so every time I trigger find all ref, it is almost the same as ctrl+shift+f, just ignoring the sting/comment.

1. for _class_ , it will take about 3-4 weeks or more.
2. for _class-methods_, If there are no different categories in your project, but the method names are the same, I think this should have a chance to be implemented, but it will only be beta for a long time.

## part-9 signature of command

> Will you do a parameter hint, for such "functions"?

Program goals <https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp#signaturehelp>

## part-10 jsdoc of type

> And most importantly, do you plan to add design support for functions with JSDoc? I mean, if I want to describe parameters, what type I expect, some description.

1. style just like jsdoc.
2. i would advise you to refer to the v2 way to mark the type.
3. i just support show the type at signature/Completion/hover, but not check. so you can mark any text, as long as you remember what it is.

## tnanks

I feel that your report, sometimes some things, because of my usage habits, do not allow me to trigger questions or think about better strategies. When someone asks a question, I can always get inspiration.

**Comment by CoffeeChaton** [comment]
> The obscure method Problem and the prompts only after i open an include are some very limiting problems. It would be fantastic if this can besolved.

> the prompts only after i open an include

`ctrl+k ctrl+o` and [Project Manager](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager)
is a good helper.

> The obscure method Problem 

processing method is very difficult for me, especially I rarely use ahk class.
Especially in open source libraries, there are few classes with simple styles.

**Comment by CzarOfScripts** [comment]
> 1. _line 11_, very look like bug, But I can't reproduce it, can you provide a minimal file with the _theme_ you are using?


I don't think line 11 is the problem. I use the theme [Monokai Mega](https://marketplace.visualstudio.com/items?itemName=jaszhix.theme-monokaiMega), which I'm still a little [modified](https://gist.github.com/CzarOfScripts/0cd16d4405ed5706d9fa04bf188d2e1a). Comments along the lines of `;*` color the extension [Better comments](https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments).
![image](https://user-images.githubusercontent.com/78804737/231384585-514c205c-2fc5-42ff-95b3-38fe3b786c09.png)

> this is by design of [Privacy Statement part 3](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp#privacy-statement).
> or you can use [Multi-root Workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces).


But it's not convenient as hell! Maybe there's a way to enable this as an option?





> 1. style just like jsdoc.

Maybe I don't understand something? This is what it looks like in JS:
![image](https://user-images.githubusercontent.com/78804737/231389410-7db717f7-e49a-453e-9316-9af4f37afb8c.png)
So with your extension:
![image](https://user-images.githubusercontent.com/78804737/231389494-4e2452de-bb01-4ab9-a11d-e15cb128a488.png)
I'm not asking for a type match, but at least a simple display of the type right next to the parameter. As we do in TypeScript.

---
I would also like to ask one more function, if it is possible. Add the same (I think it was called inline hint) hints that point to the name of the parameter in the function.
![image](https://user-images.githubusercontent.com/78804737/231390781-6c3b4906-f8d0-496d-9e8b-0761fa5d6464.png)

**Comment by CoffeeChaton** [comment]
> > 1. _line 11_, very look like bug, But I can't reproduce it, can you provide a minimal file with the _theme_ you are using?
>
> Comments along the lines of `;*` color the extension [Better comments](https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments). 

So _line 11_ is governed by Better comments? That's fine, I forgot there was this extension

> But it's not convenient as hell! Maybe there's a way to enable this as an option?

OK, will be offered as an option.

> > 1. style just like jsdoc.
> 
> Maybe I don't understand something? This is what it looks like in JS: ![image](https://user-images.githubusercontent.com/78804737/231389410-7db717f7-e49a-453e-9316-9af4f37afb8c.png) So with your extension: ![image](https://user-images.githubusercontent.com/78804737/231389494-4e2452de-bb01-4ab9-a11d-e15cb128a488.png) I'm not asking for a type match, but at least a simple display of the type right next to the parameter. As we do in TypeScript.

Not yet implemented, just plan.

> I would also like to ask one more function, if it is possible. Add the same (I think it was called inline hint) hints that point to the name of the parameter in the function. ![image](https://user-images.githubusercontent.com/78804737/231390781-6c3b4906-f8d0-496d-9e8b-0761fa5d6464.png)

will be offered as an option.

**Comment by CzarOfScripts** [comment]
- I don't understand why it was added and what it means?
![image](https://user-images.githubusercontent.com/78804737/232330028-5800dd14-9735-4e91-ac6d-454c1785a2f9.png)
---
1. I don't see that information here, is that supposed to be?
![image](https://user-images.githubusercontent.com/78804737/232330081-dead5998-0cfb-46c2-925b-b8d04721d4a9.png)

1. I expected the type to be added right next to the parameter.
![image](https://user-images.githubusercontent.com/78804737/232330623-d4aa291c-8f2b-4e1f-9086-d05a4f07a820.png)
Here's how it works with JSDoc in JS:
![image](https://user-images.githubusercontent.com/78804737/232331890-9677581e-bd7a-408b-ac88-7e5c3ded77dd.png)
![image](https://user-images.githubusercontent.com/78804737/232331972-a40fb057-d85b-47ca-90d9-d96130ed92e3.png)

---
- I also don't understand the `@param {number 0.9-1.0}` entry, does JSDoc allow to add something like `0.9-1.0`? Where did you see this syntax at all?

**Comment by CzarOfScripts** [comment]
Hi again) Note to this:
![image](https://user-images.githubusercontent.com/78804737/233749881-df95aa31-54c3-4668-a80d-2ed888ca34d6.png)
It doesn't seem to have quite the right backlighting.

**Comment by CoffeeChaton** [comment]
> * I don't understand why it was added and what it means?
>       ![image](https://user-images.githubusercontent.com/78804737/232330028-5800dd14-9735-4e91-ac6d-454c1785a2f9.png)

It implies that this function has a return value, but it should only be enabled in the following option, because other modes have already fully prompted all return values, i will fix it.

```jsonc
{
    "AhkNekoHelp.customize.signatureHelp": 0
}
```


> 1. I don't see that information here, is that supposed to be?
> ![image](https://user-images.githubusercontent.com/78804737/232330081-dead5998-0cfb-46c2-925b-b8d04721d4a9.png)

It is designed, because the API of vscode does not provide code highlighting for the part of the function signature above, but it completely repeats the parameter signature. For me, my attention is completely interrupted. You can refer to the screenshot below.

![c](https://user-images.githubusercontent.com/63182963/233788054-10d8c8af-9d62-4a02-86cc-536e68ae75a9.png)



> 2. I expected the type to be added right next to the parameter.
> ![image](https://user-images.githubusercontent.com/78804737/232330623-d4aa291c-8f2b-4e1f-9086-d05a4f07a820.png)

Will provide later.


> * I also don't understand the `@param {number 0.9-1.0}` entry, does JSDoc allow to add something like `0.9-1.0`? Where did you see this syntax at all?

This is not legal jsdco/tsdoc, I should avoid actively implying that users can write this style, the reference example will be removed, but because syntax highlighting is very difficult to match pairs of parentheses, it can only match arbitrary characters. ..until `}` is found, even if the reference example is removed, in order to avoid syntax highlighting and js parsing results being different, the behavior is still the same. Perhaps the ms python extension will be used in the future to use the diagnostic function to tell the user, Can't parse or something, but ts doesn't seem to provide any diagnostics telling me that this is illegal jsdoc/tsdoc.


![number 0 0](https://user-images.githubusercontent.com/63182963/233759314-81e72f07-8553-42ae-8ab8-8e3444bb0883.png)
> typescript parsing error, but no warning.

![py](https://user-images.githubusercontent.com/63182963/233759781-a053144e-3076-41d8-8ca6-24ed75589a4c.png)

> python provide diagnosis

**Comment by CoffeeChaton** [comment]
> ![image](https://user-images.githubusercontent.com/78804737/233749881-df95aa31-54c3-4668-a80d-2ed888ca34d6.png) 
> It doesn't seem to have quite the right backlighting.

<https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/blob/main/syntaxes/grammar/_comments_ahkexe.ahk>

It is designed, I only intend to highlight CMD of (`;@Ahk2Exe-CMD`), if the prefix `@Ahk2Exe-` is also highlighted, it is visual interference for me, if you need I can provide other tags , allowing users to set whether to use the same color scheme (such as `0x` of `0xAAAAA` [Better highlight](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp#of-numbers)), but macros/special characters/matching special rules one by one after the command, for me, the profit is very small.

**Comment by CzarOfScripts** [comment]
Hi, I decided to check if the `alt+click` transition on the `#include` path works and saw this picture:
![image](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/78804737/7885e03d-2791-4652-bd61-e7cc1ef3e855)
Only a fragment (folder) is highlighted, not the entire path.

I take it you haven't added an autocomplete for code from `#include` yet? When is this planned?
 I don't see `references` for class methods, is that not implemented either? I thought I saw in changelog that this was added, though I may be confused.

**Comment by CoffeeChaton** [comment]
![v0 0 40](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/63182963/1c7e1d0f-ac7b-4dd6-b39c-56b78dd667b7)
if your AutoHotkey NekoHelp is `v0.0.40` ?
if you can't download the latest version of the extension, then you need to up vscode.

> Hi, I decided to check if the `alt+click` transition on the `#include` path works and saw this picture: Only a fragment (folder) is highlighted, not the entire path.

![gotoDef_#Include](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/63182963/2a7c8dd9-66bc-417c-81bb-5434f84b58e3)


> I take it you haven't added an autocomplete for code from #include yet? When is this planned?

the path of `#Include c:\DEV\dev_main_P7\a1.ahk` standard token type is `String` , and vscode default settings is `"off"`, you can use the triggerCharacters `.` or use `Ctrl+Space` to call Completion.

and the next version will provide triggerCharacters  `\` and `/` to call Completion.

```jsonc
// settings.json
{
    "editor.quickSuggestions": {
        "other": "on",
        "comments": "off",
        "strings": "off" //<------ vsc default settings is "off"
    }
}
```

![Completion](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/63182963/eea38a18-1c79-40bf-b417-ac3d73f1ce42)

> I don't see `references` for class methods, is that not implemented either? I thought I saw in changelog that this was added, though I may be confused.

check

```jsonc
// settings.json
{
    "AhkNekoHelp.method": {
        "gotoDef": "precision_mode",
        "hover": "precision_mode",
        "findAllRef": "precision_mode",
        "CodeLens": "none"
    }
}
```

**Comment by CzarOfScripts** [comment]
For starters, yes with v0.0.40, you do not understand. Transition works, but when I press `alt` and hover the cursor - only a fragment of the entire path is highlighted, not the entire path.

Second, I mean that I don't get hints from `#include` files, not the autocomplete for the path itself.

Third:
![image](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/78804737/1cb615b4-9a3f-4632-968c-36e4bf9a2cbb)

**Comment by CoffeeChaton** [comment]
![goto def of `#include` underlined](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/63182963/6b98861b-3537-474f-b8a6-a64a0975aacb)
> 1. fix it now, and released at next version (`v0.0.41`)

![v0 0 41](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/63182963/a095f6c7-42b3-452d-a84c-f764ee347337)
> 2. Already written, in testing, `v0.0.41` not released yet.

https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/63182963/36e6823d-91be-4e9c-9638-e092ac6eb0a5
> 3. My test is OK, or you can change the option to `"loose_mode"` or `"precision_or_loose_mode"`

---
there are too many extended Issues, and I can't track it effectively. After the next version is released, I will close and split this it to a new issues.

**Comment by CzarOfScripts** [comment]
@CoffeeChaton, is it supposed to be like that?

![image](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/78804737/c30ee80e-9813-4368-a34e-3fa4586fde14)

**Comment by CoffeeChaton** [comment]
> @CoffeeChaton, is it supposed to be like that?
> 

1. underlined is expected.
2. hover and get `class` key word doc, not expected.
